spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mmys.c7h42dsnyxdl.ap-northeast-2.rds.amazonaws.com:3306/hr
    username: wjsw
    password: test1234
  jpa:
    hibernate:
      ddl-auto: update
  mvc:
    path match:
      matching-strategy: ant_path_matcher



security:
  myapp:
    key: koIDyUGqlic4RW3BT%2F0jpFe6QAyurUul%2B5ptcvujSy02%2FXtypSeDpl6uukW7y48MtbyPkVkKUbxy73%2F5hcYGbQ%3D%3D
